name: CovidUI Project
author: FelixTatsumaki
description: "Hanya Project CovidUI"
main: FelixTatsumaki\main
version: 1.0.0
api: [3.0.0-ALPHA12, 3.0.0, 3.1.1, 3.0.2, 4.0.0]

commands:
 covidmenu:
   Description: "Anda Sembuh bakalan Cok"